version: '3.7'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/app/src
    environment:
      PROJECT_NAME: 'School Management'
      JWT_KEY: 'sec$Et10231819821^%&'
      JWT_TOKEN_EXPIRY: '3600'
      IS_PRODUCTION: 'false'
      FRONTEND_DOMAIN_NAME: 'http://localhost:3000'
      IS_TESTING: 'false'
      TYPEORM_DATABASE: 'schooldb'
      TYPEORM_USERNAME: 'schooldb_user'
      TYPEORM_PASSWORD: 'password'
      TYPEORM_HOST: 'db'
      TYPEORM_PORT: '3306'
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_URL: 'http://localhost:8080/api'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    depends_on:
      - server
  db:
    image: library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: schooldb_user
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - '3306:3306'
    entrypoint:
      sh -c "
        echo '
        CREATE SCHEMA IF NOT EXISTS schooldb;
        GRANT ALL PRIVILEGES ON schooldb.* TO '\''schooldb_user'\''@'\''%'\'' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        '
        > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "